hash-format = "sha256"

[[files]]
file = "mods/brandons-core.pw.toml"
hash = "08393165e5ae600c6b2ccbafdb7af4690e228dbef7fa2e90ba6fb5e65b8a4499"
metafile = true

[[files]]
file = "mods/draconic-evolution.pw.toml"
hash = "327dab8a49d15cab0bdfbb6ee28773f835fcc4b281deec2b8bccdbbf3fcf1b6f"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "74347b055c8c520681d3e412ea9d23d645898685aaa19db6ebd74e0ff49c9cdc"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "0b8d3c2d4af90a8df7eeabe66fb4811da495d51f9fcc3df96ab65adba4fbd07a"
metafile = true
